### ISSUE TITLE
Safari deletes ADFS cookies when closing browser

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-adfs-idprovider#12] opened 2018-09-11 07:56 UTC
When browser is closed, Safari deletes the cookies used for storing logged in user sessions. Other browsers, like Chrome, does not do this.

**Comment by Bellfalasch** [comment] 2018-09-11 12:10
Additional error details (from Safari):

Det oppstod en feil 
Det oppstod en feil. Kontakt administratoren for mer informasjon. 
Feilopplysninger
·         Activity ID: 148c5d08-7e5d-4b2b-7911-0080010000f5
·         Relying party: Enonic
·         Error time: Tue, 11 Sep 2018 08:02:22 GMT
·         Cookie: enabled
·         User agent string: Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1

**Comment by Bellfalasch** [comment] 2018-09-12 09:09
More details from the users testing it (just ask if you need it translated):

"Da har jeg testet fra privat PC. Windows 10 og IE 11 (11.228.17134.0).

Lukker jeg kun fanen og så forsøker å åpne intranettet kommer jeg rett inn uten ny innlogging.

Lukker jeg IE og forsøker å åpne intranettet kommer innloggingssiden opp igjen, men med brukernavn og passord ferdig utfylt slik at jeg bare trenger å trykke på knappen "Logg på" for å få opp intranettet."

Meaning they close the tab: still logged in. The close the entire window/app: need to log in again. This might be something we cannot do anything about, related to "garbage collection" for cookies, and settings for that? But would be nice to check it out and know if it is possible to bypass.

**Comment by GlennRicaud** [comment] 2018-09-14 08:02
@bwe:
It is not just Safari but all browsers from what I see.
The cookies set for both Enonic XP and ADFS seem to be session cookies. So it normal that when closing the browser you need to log again (except if there is session restoring).

So not a bug. More a feature request. Actually, it is more configuration: I think that in ADFS, you can enable a "Keep me signed-in option".
  ```Set-AdfsProperties -EnableKmsi:$true```

**Comment by Bellfalasch** [comment] 2018-09-18 08:29
Thanks @GlennRicaud this seems to have solved the issue.

**Closed** 2018-09-26 07:08 UTC
Labels: enhancement
